In [1]:
import pandas as pd
import numpy as np

In [2]:
col_names = ['Prix','Vitesse_Max','Conso_moy','Dis_freinage','Confort','Vol_Coffre','Acceleration']

col_names = ['g1','g2','g3','g4','g5','g6','g7']

In [3]:
data_voiture = pd.read_csv('data/donnees.csv', names=col_names)

In [4]:
data_voiture

,Prix,Vitesse_Max,Conso_moy,Dis_freinage,Confort,Vol_Coffre,Acceleration
0,23817,201,8.0,39.6,6,378,31.2
1,25771,195,5.7,35.8,7,440,33.0
2,25496,195,7.9,37.0,2,480,34.0
3,25649,191,8.3,34.4,2,430,34.6
4,26183,199,7.8,35.7,5,494,32.0
5,23664,194,7.7,37.4,4,452,33.8
6,23344,195,7.6,34.4,3,475,33.6
7,26260,209,6.6,36.6,4,440,30.9
8,19084,182,6.4,40.6,8,408,33.5
9,29160,203,7.5,34.5,1,520,32.0

In [5]:
poids = [0.2, 0.1, 0.15, 0.15, 0.1, 0.1, 0.2]

In [6]:
scores = np.dot(data_voiture, poids)

In [7]:
scores

array([4835.28 , 5231.225, 5180.435, 5205.425, 5319.325, 4811.325,
       4749.12 , 5329.96 , 3890.35 , 5917.1  ])

In [8]:
data_voiture["Score"] = scores

In [9]:
data_voiture = data_voiture.sort_values(by="Score", ascending=False)

In [10]:
data_voiture

,Prix,Vitesse_Max,Conso_moy,Dis_freinage,Confort,Vol_Coffre,Acceleration,Score
9,29160,203,7.5,34.5,1,520,32.0,5917.100
7,26260,209,6.6,36.6,4,440,30.9,5329.960
4,26183,199,7.8,35.7,5,494,32.0,5319.325
1,25771,195,5.7,35.8,7,440,33.0,5231.225
3,25649,191,8.3,34.4,2,430,34.6,5205.425
2,25496,195,7.9,37.0,2,480,34.0,5180.435
0,23817,201,8.0,39.6,6,378,31.2,4835.280
5,23664,194,7.7,37.4,4,452,33.8,4811.325
6,23344,195,7.6,34.4,3,475,33.6,4749.120
8,19084,182,6.4,40.6,8,408,33.5,3890.350

In [11]:
# Promethe

In [12]:
pip install pyMCDA

Requirement already satisfied: pyMCDA in c:\users\niang\anaconda3\lib\site-packages (0.4)
Requirement already satisfied: numpy in c:\users\niang\anaconda3\lib\site-packages (from pyMCDA) (1.21.5)
Note: you may need to restart the kernel to use updated packages.

In [13]:
preference_functions = {
    "Prix": "min",
    "Vitesse_Max": "max",
    "Conso_moy": "min",
    "Dis_freinage": "min",
    "Confort": "max",
    "Vol_Coffre": "max",
    "Acceleration": "max"
}

In [14]:
normalized_df = (data_voiture - data_voiture.min()) / (data_voiture.max() - data_voiture.min())

In [15]:
normalized_df

,Prix,Vitesse_Max,Conso_moy,Dis_freinage,Confort,Vol_Coffre,Acceleration,Score
9,1.000000,0.777778,0.692308,0.016129,0.000000,1.000000,0.297297,1.000000
7,0.712187,1.000000,0.346154,0.354839,0.428571,0.436620,0.000000,0.710305
4,0.704545,0.629630,0.807692,0.209677,0.571429,0.816901,0.297297,0.705057
1,0.663656,0.481481,0.000000,0.225806,0.857143,0.436620,0.567568,0.661589
3,0.651548,0.333333,1.000000,0.000000,0.142857,0.366197,1.000000,0.648859
2,0.636364,0.481481,0.846154,0.419355,0.142857,0.718310,0.837838,0.636529
0,0.469730,0.703704,0.884615,0.838710,0.714286,0.000000,0.081081,0.466229
5,0.454545,0.444444,0.769231,0.483871,0.428571,0.521127,0.783784,0.454410
6,0.422787,0.481481,0.730769,0.000000,0.285714,0.683099,0.729730,0.423718
8,0.000000,0.000000,0.269231,1.000000,1.000000,0.211268,0.702703,0.000000

In [16]:
# Calculer les indices PROMETHEE (P et D)
P_indices = np.zeros((len(data_voiture), len(data_voiture)))
D_indices = np.zeros((len(data_voiture), len(data_voiture)))

In [17]:
D_indices

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [18]:
for i in range(len(data_voiture)):
    for j in range(len(data_voiture)):
        if i != j:
            for critere, preference in preference_functions.items():
                if preference == "min":
                    P_indices[i, j] += np.maximum(0, normalized_df.iloc[i][critere] - normalized_df.iloc[j][critere])
                elif preference == "max":
                    P_indices[i, j] += np.maximum(0, normalized_df.iloc[j][critere] - normalized_df.iloc[i][critere])
                D_indices[i, j] += np.abs(normalized_df.iloc[i][critere] - normalized_df.iloc[j][critere])

In [19]:
P_global = P_indices.sum(axis=1) - P_indices.sum(axis=0)
D_global = D_indices.sum(axis=1) - D_indices.sum(axis=0)

In [22]:
# Classement final
scores = P_global - D_global
data_voiture["Score"] = scores
data_voiture = data_voiture.sort_values(by="Score", ascending=False)

In [23]:
data_voiture

,Prix,Vitesse_Max,Conso_moy,Dis_freinage,Confort,Vol_Coffre,Acceleration,Score
0,23817,201,8.0,39.6,6,378,31.2,11.722142
3,25649,191,8.3,34.4,2,430,34.6,2.873902
2,25496,195,7.9,37.0,2,480,34.0,1.996156
9,29160,203,7.5,34.5,1,520,32.0,1.115912
7,26260,209,6.6,36.6,4,440,30.9,0.262184
5,23664,194,7.7,37.4,4,452,33.8,0.079504
4,26183,199,7.8,35.7,5,494,32.0,-1.151121
8,19084,182,6.4,40.6,8,408,33.5,-1.665100
6,23344,195,7.6,34.4,3,475,33.6,-5.482385
1,25771,195,5.7,35.8,7,440,33.0,-9.751194

In [1]:
import numpy as np
import pandas as pd

def process_data(data, poids):
    nb_candidats = len(data)
    comparaison_matrice = np.zeros((nb_candidats, nb_candidats))

    # Compare les candidats deux à deux en conservant les poids pertinents
    for i in range(nb_candidats):
        for j in range(nb_candidats):
            if i != j:
                for k in range(len(poids)):
                    if data.iloc[i, k] >= data.iloc[j, k]:
                        comparaison_matrice[i, j] += poids[k]

    print("Matrice de comparaison des candidats :")
    print(comparaison_matrice)

    flux_positif = comparaison_matrice.sum(axis=0)
    flux_negatif = comparaison_matrice.sum(axis=1)

    # Récupérer les noms des candidats à partir des premières valeurs de chaque ligne
    candidat_names = [data.iloc[i, 0] for i in range(nb_candidats)]

    flux_dict_po = {candidat_names[i]: flux for i, flux in enumerate(flux_positif)}
    print("Dictionnaire des valeurs de flux associées aux candidats (Flux Positif):")
    print(flux_dict_po)

    flux_dict_neg = {candidat_names[i]: flux for i, flux in enumerate(flux_negatif)}
    print("Dictionnaire des valeurs de flux associées aux candidats (Flux Négatif):")
    print(flux_dict_neg)

    sorted_candidats_po = sorted(flux_dict_po, key=lambda candidat: flux_dict_po[candidat], reverse=True)
    print("Ordre des candidats en fonction des valeurs de flux positif (ordre décroissant):")
    for i, candidat in enumerate(sorted_candidats_po, start=1):
        print(f"Position {i}: {candidat}")

    sorted_candidats_neg = sorted(flux_dict_neg, key=lambda candidat: flux_dict_neg[candidat])
    print("Ordre des candidats en fonction des valeurs de flux négatif (ordre croissant):")
    for i, candidat in enumerate(sorted_candidats_neg, start=1):
        print(f"Position {i}: {candidat}")

# Exemple d'utilisation avec des données Pandas
data = pd.DataFrame({
    'Candidat': ['A1', 'A2', 'A3', 'A4', 'A5', 'A6'],
    'C1': [16, 10, 18, 18, 16, 6],
    'C2': [14, 18, 12, 4, 10, 14],
    'C3': [16, 12, 6, 20, 12, 18]
})

poids = [0.6, 0.1, 0.3]

process_data(data, poids)

Matrice de comparaison des candidats :
[[0.  0.1 0.3 0.3 0.4 0.4]
 [0.9 0.  0.3 0.3 0.3 0.4]
 [0.7 0.7 0.  0.4 0.4 0.1]
 [0.7 0.7 0.7 0.  0.1 0.1]
 [0.7 0.7 0.6 0.9 0.  0.1]
 [0.9 0.6 0.9 0.9 0.9 0. ]]
Dictionnaire des valeurs de flux associées aux candidats (Flux Positif):
{'A1': 3.9, 'A2': 2.8000000000000003, 'A3': 2.8, 'A4': 2.8, 'A5': 2.1, 'A6': 1.1}
Dictionnaire des valeurs de flux associées aux candidats (Flux Négatif):
{'A1': 1.5, 'A2': 2.2, 'A3': 2.3, 'A4': 2.3, 'A5': 3.0, 'A6': 4.199999999999999}
Ordre des candidats en fonction des valeurs de flux positif (ordre décroissant):
Position 1: A1
Position 2: A2
Position 3: A3
Position 4: A4
Position 5: A5
Position 6: A6
Ordre des candidats en fonction des valeurs de flux négatif (ordre croissant):
Position 1: A1
Position 2: A2
Position 3: A3
Position 4: A4
Position 5: A5
Position 6: A6

In [2]:
data

  Candidat  C1  C2  C3
0       A1  16  14  16
1       A2  10  18  12
2       A3  18  12   6
3       A4  18   4  20
4       A5  16  10  12
5       A6   6  14  18